/**
 * AI Image Generator Module for MasonArt Platform
 *
 * Provides AI image generation capabilities using multiple providers:
 * - Replicate (Stable Diffusion SDXL)
 * - OpenAI (DALL-E 3)
 * - FAL.ai (FLUX, SDXL)
 *
 * Based on patterns from docs/poster-app-tech-stack.md
 */

import type {
  AIStylePreset,
  AIAspectRatio,
  AIModelProvider,
} from "../database/schema/ai-generations";
import {
  STYLE_PRESETS,
  constructEnhancedPrompt,
  constructNegativePrompt,
  getImageDimensions,
} from "./style-presets";

// ============================================================================
// Type Definitions
// ============================================================================

/**
 * Input for AI image generation
 */
export interface AIGenerationInput {
  /** User's text prompt */
  prompt: string;
  /** Optional negative prompt */
  negativePrompt?: string;
  /** Style preset to apply */
  stylePreset: AIStylePreset;
  /** Aspect ratio for the output */
  aspectRatio: AIAspectRatio;
  /** Optional color mood */
  colorMood?: string;
  /** Optional specific color palette */
  colorPalette?: string[];
  /** Seed for reproducibility (optional) */
  seed?: number;
  /** AI model provider to use */
  provider?: AIModelProvider;
}

/**
 * Generated image result
 */
export interface GeneratedImage {
  /** Image data as Buffer */
  buffer: Buffer;
  /** Image URL (if generated by provider) */
  url?: string;
  /** Width in pixels */
  width: number;
  /** Height in pixels */
  height: number;
  /** Seed used for generation */
  seed: number;
  /** Variation index (0-based) */
  variationIndex: number;
  /** MIME type */
  mimeType: string;
}

/**
 * Generation result from AI provider
 */
export interface AIGenerationResult {
  /** Whether generation was successful */
  success: boolean;
  /** Generated images */
  images: GeneratedImage[];
  /** Enhanced prompt that was used */
  enhancedPrompt: string;
  /** Negative prompt that was used */
  negativePrompt: string;
  /** Model provider used */
  provider: AIModelProvider;
  /** Model version/identifier */
  modelVersion?: string;
  /** Processing time in milliseconds */
  processingTimeMs: number;
  /** Error message if failed */
  error?: string;
  /** Cost in cents (if available) */
  costCents?: number;
}

/**
 * Provider-specific configuration
 */
export interface AIProviderConfig {
  /** API key */
  apiKey: string;
  /** API endpoint (for custom endpoints) */
  endpoint?: string;
  /** Model identifier */
  modelId: string;
  /** Timeout in milliseconds */
  timeout: number;
}

// ============================================================================
// Provider Configurations
// ============================================================================

/**
 * Replicate model identifiers
 */
export const REPLICATE_MODELS = {
  sdxl: "stability-ai/sdxl:7762fd07cf82c948538e41f63f77d685e02b063e37e496e96eefd46c929f9bdc",
  sdxlLightning: "bytedance/sdxl-lightning-4step:5f24084160c9089501c1b3545d9be3c27883ae2239b6f412990e82d4a6210f8f",
  flux: "black-forest-labs/flux-schnell",
  fluxPro: "black-forest-labs/flux-pro",
} as const;

/**
 * OpenAI model identifiers
 */
export const OPENAI_MODELS = {
  dalleE3: "dall-e-3",
} as const;

/**
 * FAL.ai model identifiers
 */
export const FAL_MODELS = {
  fluxSchnell: "fal-ai/flux/schnell",
  fluxDev: "fal-ai/flux/dev",
  sdxl: "fal-ai/fast-sdxl",
} as const;

// ============================================================================
// Environment Configuration
// ============================================================================

/**
 * Get provider configuration from environment
 */
function getProviderConfig(provider: AIModelProvider): AIProviderConfig | null {
  switch (provider) {
    case "stable-diffusion":
      const replicateKey = process.env.REPLICATE_API_TOKEN;
      if (!replicateKey) return null;
      return {
        apiKey: replicateKey,
        modelId: REPLICATE_MODELS.sdxl,
        timeout: 120000, // 2 minutes
      };

    case "dall-e-3":
      const openaiKey = process.env.OPENAI_API_KEY;
      if (!openaiKey) return null;
      return {
        apiKey: openaiKey,
        modelId: OPENAI_MODELS.dalleE3,
        timeout: 60000, // 1 minute
      };

    case "fal-ai":
      const falKey = process.env.FAL_API_KEY;
      if (!falKey) return null;
      return {
        apiKey: falKey,
        modelId: FAL_MODELS.fluxSchnell,
        timeout: 90000, // 1.5 minutes
      };

    default:
      return null;
  }
}

/**
 * Check if a provider is configured and available
 */
export function isProviderAvailable(provider: AIModelProvider): boolean {
  return getProviderConfig(provider) !== null;
}

/**
 * Get the first available provider
 */
export function getAvailableProvider(): AIModelProvider | null {
  const providers: AIModelProvider[] = ["stable-diffusion", "dall-e-3", "fal-ai"];
  for (const provider of providers) {
    if (isProviderAvailable(provider)) {
      return provider;
    }
  }
  return null;
}

// ============================================================================
// Main Generation Function
// ============================================================================

/**
 * Generate AI images using the specified provider
 *
 * @param input - Generation input parameters
 * @param variationCount - Number of variations to generate (1-4)
 * @returns Generation result with images
 */
export async function generateImages(
  input: AIGenerationInput,
  variationCount: number = 4
): Promise<AIGenerationResult> {
  const startTime = Date.now();
  const provider = input.provider || getAvailableProvider() || "stable-diffusion";
  const config = getProviderConfig(provider);

  if (!config) {
    return {
      success: false,
      images: [],
      enhancedPrompt: input.prompt,
      negativePrompt: input.negativePrompt || "",
      provider,
      processingTimeMs: Date.now() - startTime,
      error: `AI provider ${provider} is not configured. Please set the appropriate API key.`,
    };
  }

  // Construct enhanced prompts
  const enhancedPrompt = constructEnhancedPrompt(input.prompt, input.stylePreset, {
    colorMood: input.colorMood,
    colorPalette: input.colorPalette,
  });

  const negativePrompt = constructNegativePrompt(
    input.stylePreset,
    input.negativePrompt
  );

  // Get dimensions for the provider
  const dimensions = getImageDimensions(input.aspectRatio, provider);

  try {
    let images: GeneratedImage[];

    switch (provider) {
      case "stable-diffusion":
        images = await generateWithReplicate(
          config,
          enhancedPrompt,
          negativePrompt,
          dimensions,
          variationCount,
          input.seed
        );
        break;

      case "dall-e-3":
        images = await generateWithOpenAI(
          config,
          enhancedPrompt,
          dimensions,
          variationCount,
          input.seed
        );
        break;

      case "fal-ai":
        images = await generateWithFalAI(
          config,
          enhancedPrompt,
          negativePrompt,
          dimensions,
          variationCount,
          input.seed
        );
        break;

      default:
        throw new Error(`Unsupported provider: ${provider}`);
    }

    return {
      success: true,
      images,
      enhancedPrompt,
      negativePrompt,
      provider,
      modelVersion: config.modelId,
      processingTimeMs: Date.now() - startTime,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
    return {
      success: false,
      images: [],
      enhancedPrompt,
      negativePrompt,
      provider,
      modelVersion: config.modelId,
      processingTimeMs: Date.now() - startTime,
      error: errorMessage,
    };
  }
}

// ============================================================================
// Replicate Provider (Stable Diffusion SDXL)
// ============================================================================

/**
 * Generate images using Replicate API (Stable Diffusion SDXL)
 */
async function generateWithReplicate(
  config: AIProviderConfig,
  prompt: string,
  negativePrompt: string,
  dimensions: { width: number; height: number },
  variationCount: number,
  baseSeed?: number
): Promise<GeneratedImage[]> {
  const images: GeneratedImage[] = [];

  // Replicate prediction API endpoint
  const endpoint = config.endpoint || "https://api.replicate.com/v1/predictions";

  for (let i = 0; i < variationCount; i++) {
    const seed = baseSeed !== undefined ? baseSeed + i : Math.floor(Math.random() * 2147483647);

    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        Authorization: `Token ${config.apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        version: config.modelId.split(":")[1],
        input: {
          prompt,
          negative_prompt: negativePrompt,
          width: dimensions.width,
          height: dimensions.height,
          seed,
          num_outputs: 1,
          guidance_scale: 7.5,
          num_inference_steps: 30,
          scheduler: "DPM++ 2M Karras",
        },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Replicate API error: ${response.status} - ${errorText}`);
    }

    const prediction = (await response.json()) as {
      id: string;
      urls: { get: string };
      status: string;
    };

    // Poll for completion
    const result = await pollReplicatePrediction(config.apiKey, prediction.urls.get, config.timeout);

    if (result.status === "succeeded" && result.output && Array.isArray(result.output)) {
      const imageUrl = result.output[0] as string;
      const imageBuffer = await fetchImageAsBuffer(imageUrl);

      images.push({
        buffer: imageBuffer,
        url: imageUrl,
        width: dimensions.width,
        height: dimensions.height,
        seed,
        variationIndex: i,
        mimeType: "image/png",
      });
    } else if (result.status === "failed") {
      throw new Error(`Replicate prediction failed: ${result.error || "Unknown error"}`);
    }
  }

  return images;
}

/**
 * Poll Replicate prediction status until completion
 */
async function pollReplicatePrediction(
  apiKey: string,
  url: string,
  timeout: number
): Promise<{
  status: string;
  output?: unknown[];
  error?: string;
}> {
  const startTime = Date.now();
  const pollInterval = 1000; // 1 second

  while (Date.now() - startTime < timeout) {
    const response = await fetch(url, {
      headers: {
        Authorization: `Token ${apiKey}`,
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to poll prediction: ${response.status}`);
    }

    const prediction = (await response.json()) as {
      status: string;
      output?: unknown[];
      error?: string;
    };

    if (prediction.status === "succeeded" || prediction.status === "failed") {
      return prediction;
    }

    // Wait before polling again
    await sleep(pollInterval);
  }

  throw new Error("Prediction timed out");
}

// ============================================================================
// OpenAI Provider (DALL-E 3)
// ============================================================================

/**
 * Generate images using OpenAI DALL-E 3 API
 */
async function generateWithOpenAI(
  config: AIProviderConfig,
  prompt: string,
  dimensions: { width: number; height: number },
  variationCount: number,
  baseSeed?: number
): Promise<GeneratedImage[]> {
  const images: GeneratedImage[] = [];

  // DALL-E 3 endpoint
  const endpoint = config.endpoint || "https://api.openai.com/v1/images/generations";

  // Map dimensions to DALL-E 3 supported sizes
  const size = mapToDalleSize(dimensions);

  // DALL-E 3 only generates 1 image per request
  for (let i = 0; i < variationCount; i++) {
    const seed = baseSeed !== undefined ? baseSeed + i : Math.floor(Math.random() * 2147483647);

    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: config.modelId,
        prompt,
        n: 1,
        size,
        quality: "standard",
        response_format: "url",
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`OpenAI API error: ${response.status} - ${errorText}`);
    }

    const result = (await response.json()) as {
      data: Array<{ url: string; revised_prompt?: string }>;
    };

    if (result.data && result.data.length > 0 && result.data[0]) {
      const imageUrl = result.data[0].url;
      const imageBuffer = await fetchImageAsBuffer(imageUrl);

      images.push({
        buffer: imageBuffer,
        url: imageUrl,
        width: dimensions.width,
        height: dimensions.height,
        seed, // DALL-E doesn't use seeds, but we track it for consistency
        variationIndex: i,
        mimeType: "image/png",
      });
    }
  }

  return images;
}

/**
 * Map dimensions to DALL-E 3 supported sizes
 */
function mapToDalleSize(dimensions: { width: number; height: number }): string {
  const { width, height } = dimensions;

  // DALL-E 3 supported sizes: 1024x1024, 1024x1792, 1792x1024
  if (width === height) {
    return "1024x1024";
  } else if (height > width) {
    return "1024x1792";
  } else {
    return "1792x1024";
  }
}

// ============================================================================
// FAL.ai Provider
// ============================================================================

/**
 * Generate images using FAL.ai API
 */
async function generateWithFalAI(
  config: AIProviderConfig,
  prompt: string,
  negativePrompt: string,
  dimensions: { width: number; height: number },
  variationCount: number,
  baseSeed?: number
): Promise<GeneratedImage[]> {
  const images: GeneratedImage[] = [];

  // FAL.ai endpoint
  const endpoint = `https://fal.run/${config.modelId}`;

  for (let i = 0; i < variationCount; i++) {
    const seed = baseSeed !== undefined ? baseSeed + i : Math.floor(Math.random() * 2147483647);

    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        Authorization: `Key ${config.apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
        negative_prompt: negativePrompt,
        image_size: {
          width: dimensions.width,
          height: dimensions.height,
        },
        seed,
        num_images: 1,
        sync_mode: true,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`FAL.ai API error: ${response.status} - ${errorText}`);
    }

    const result = (await response.json()) as {
      images: Array<{ url: string; width: number; height: number }>;
    };

    if (result.images && result.images.length > 0 && result.images[0]) {
      const imageData = result.images[0];
      const imageBuffer = await fetchImageAsBuffer(imageData.url);

      images.push({
        buffer: imageBuffer,
        url: imageData.url,
        width: imageData.width ?? dimensions.width,
        height: imageData.height ?? dimensions.height,
        seed,
        variationIndex: i,
        mimeType: "image/png",
      });
    }
  }

  return images;
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Fetch an image URL and return as Buffer
 */
async function fetchImageAsBuffer(url: string): Promise<Buffer> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch image: ${response.status}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

/**
 * Sleep for specified milliseconds
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ============================================================================
// Content Moderation
// ============================================================================

/**
 * Check if a prompt contains banned content
 *
 * @param prompt - The prompt to check
 * @param bannedPatterns - Array of banned patterns (regex strings)
 * @returns Object indicating if content is safe and any matched patterns
 */
export function checkPromptModeration(
  prompt: string,
  bannedPatterns: Array<{ pattern: string; isRegex: boolean; category: string }>
): {
  isSafe: boolean;
  matchedPatterns: Array<{ pattern: string; category: string }>;
  riskScore: number;
} {
  const lowerPrompt = prompt.toLowerCase();
  const matchedPatterns: Array<{ pattern: string; category: string }> = [];

  for (const bannedPattern of bannedPatterns) {
    let isMatch = false;

    if (bannedPattern.isRegex) {
      try {
        const regex = new RegExp(bannedPattern.pattern, "i");
        isMatch = regex.test(prompt);
      } catch {
        // Invalid regex, skip
        continue;
      }
    } else {
      isMatch = lowerPrompt.includes(bannedPattern.pattern.toLowerCase());
    }

    if (isMatch) {
      matchedPatterns.push({
        pattern: bannedPattern.pattern,
        category: bannedPattern.category,
      });
    }
  }

  // Calculate risk score based on number and severity of matches
  const riskScore = Math.min(matchedPatterns.length * 0.25, 1.0);

  return {
    isSafe: matchedPatterns.length === 0,
    matchedPatterns,
    riskScore,
  };
}

// ============================================================================
// Generation Helpers
// ============================================================================

/**
 * Estimate generation cost in cents for a given configuration
 */
export function estimateGenerationCost(
  provider: AIModelProvider,
  variationCount: number
): number {
  // Approximate costs per image in cents
  const costPerImage: Record<AIModelProvider, number> = {
    "stable-diffusion": 2, // ~$0.02 per image on Replicate
    "dall-e-3": 8, // ~$0.08 per image (standard quality)
    midjourney: 10, // ~$0.10 per image (estimate)
    "fal-ai": 1, // ~$0.01 per image (FLUX Schnell)
  };

  return (costPerImage[provider] || 5) * variationCount;
}

/**
 * Get estimated generation time in seconds
 */
export function estimateGenerationTime(
  provider: AIModelProvider,
  variationCount: number
): number {
  // Approximate time per image in seconds
  const timePerImage: Record<AIModelProvider, number> = {
    "stable-diffusion": 15, // ~15s per image on Replicate SDXL
    "dall-e-3": 10, // ~10s per image on DALL-E 3
    midjourney: 30, // ~30s per image
    "fal-ai": 5, // ~5s per image (FLUX Schnell is fast)
  };

  // Add some overhead time for API calls
  const overhead = 5;

  return (timePerImage[provider] || 15) * variationCount + overhead;
}

/**
 * Get style preset configuration for display
 */
export function getStylePresetInfo(stylePreset: AIStylePreset): {
  name: string;
  description: string;
  keywords: string[];
  category: string;
  isPremium: boolean;
} | null {
  const preset = STYLE_PRESETS[stylePreset];
  if (!preset) return null;

  return {
    name: preset.name,
    description: preset.description,
    keywords: preset.keywords,
    category: preset.category,
    isPremium: preset.isPremium,
  };
}

/**
 * Validate generation input
 */
export function validateGenerationInput(input: AIGenerationInput): {
  isValid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check prompt
  if (!input.prompt || input.prompt.trim().length === 0) {
    errors.push("Prompt is required");
  } else if (input.prompt.length > 2000) {
    errors.push("Prompt must be 2000 characters or less");
  }

  // Check style preset
  if (!STYLE_PRESETS[input.stylePreset]) {
    errors.push(`Invalid style preset: ${input.stylePreset}`);
  }

  // Check aspect ratio
  const validAspectRatios: AIAspectRatio[] = ["square", "portrait", "landscape", "panoramic"];
  if (!validAspectRatios.includes(input.aspectRatio)) {
    errors.push(`Invalid aspect ratio: ${input.aspectRatio}`);
  }

  // Check seed if provided
  if (input.seed !== undefined && (input.seed < 0 || input.seed > 2147483647)) {
    errors.push("Seed must be between 0 and 2147483647");
  }

  return {
    isValid: errors.length === 0,
    errors,
  };
}

