/**
 * Video Processing Tests
 *
 * Exercises the real ffmpeg/ffprobe binaries against a fixture generated at
 * runtime by ffmpeg itself, so no binary blob is committed to the repo.
 *
 * The fixture is deliberately mpeg4 video + mp3 audio: that is what a
 * normalisation step has to convert *away from*, so the transcode assertions
 * (h264 + aac) prove work actually happened rather than passing trivially.
 *
 * The suite skips when ffmpeg is absent (same shape as SKIP_DB_RUNTIME_TESTS).
 * Local dev on macOS needs `brew install ffmpeg`.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtemp, rm, writeFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import sharp from 'sharp';
import '../setup';

import {
  isFfmpegAvailable,
  probeVideo,
  transcodeToMp4,
  extractPosterFrame,
  VideoProcessingError,
} from '../../src/lib/video-processing';

/**
 * Detect ffmpeg synchronously so `describe.skipIf` can be evaluated at
 * collection time.
 */
function ffmpegOnPath(): boolean {
  try {
    const result = spawnSync('ffmpeg', ['-version'], { stdio: 'ignore' });
    return result.status === 0;
  } catch {
    return false;
  }
}

const SKIP_TESTS =
  process.env.SKIP_FFMPEG_TESTS === 'true' || !ffmpegOnPath();

if (SKIP_TESTS) {
  console.log(
    '⏭️  Skipping video processing tests (ffmpeg not on PATH - `brew install ffmpeg`)'
  );
}

// ffmpeg work is slow relative to vitest's 5s default
const FFMPEG_TIMEOUT = 30_000;

describe.skipIf(SKIP_TESTS)('video-processing', () => {
  let workDir: string;
  let fixturePath: string;

  beforeAll(async () => {
    workDir = await mkdtemp(join(tmpdir(), 'video-processing-test-'));
    fixturePath = join(workDir, 'fixture.mp4');

    // 2 second, 320x240, mpeg4 + mp3 - generated by ffmpeg's own synthetic
    // sources so the repo carries no binary fixture.
    const result = spawnSync(
      'ffmpeg',
      [
        '-hide_banner',
        '-loglevel',
        'error',
        '-f',
        'lavfi',
        '-i',
        'testsrc=duration=2:size=320x240:rate=10',
        '-f',
        'lavfi',
        '-i',
        'sine=frequency=440:duration=2',
        '-pix_fmt',
        'yuv420p',
        '-c:v',
        'mpeg4',
        '-c:a',
        'libmp3lame',
        '-shortest',
        '-y',
        fixturePath,
      ],
      { encoding: 'utf8' }
    );

    if (result.status !== 0) {
      throw new Error(`Failed to generate fixture clip: ${result.stderr}`);
    }
  }, FFMPEG_TIMEOUT);

  afterAll(async () => {
    if (workDir) {
      await rm(workDir, { recursive: true, force: true });
    }
  });

  describe('isFfmpegAvailable', () => {
    it('returns true when ffmpeg is installed', async () => {
      await expect(isFfmpegAvailable()).resolves.toBe(true);
    });

    it('returns false when PATH is emptied', async () => {
      const originalPath = process.env.PATH;
      const originalOverride = process.env.FFMPEG_PATH;
      process.env.PATH = '';
      delete process.env.FFMPEG_PATH;

      try {
        await expect(isFfmpegAvailable()).resolves.toBe(false);
      } finally {
        process.env.PATH = originalPath;
        if (originalOverride !== undefined) {
          process.env.FFMPEG_PATH = originalOverride;
        }
      }
    });
  });

  describe('probeVideo', () => {
    it('reports duration, dimensions and codecs', async () => {
      const metadata = await probeVideo(fixturePath);

      expect(metadata.durationSeconds).toBeGreaterThan(1.8);
      expect(metadata.durationSeconds).toBeLessThan(2.2);
      expect(metadata.width).toBe(320);
      expect(metadata.height).toBe(240);
      expect(metadata.videoCodec).toBe('mpeg4');
      expect(metadata.audioCodec).toBe('mp3');
      expect(metadata.hasAudio).toBe(true);
      expect(metadata.sizeBytes).toBeGreaterThan(0);
    }, FFMPEG_TIMEOUT);

    it('rejects with a typed error carrying ffmpeg stderr for a non-video file', async () => {
      const notAVideo = join(workDir, 'not-a-video.mp4');
      await writeFile(notAVideo, 'this is plainly not a video');

      await expect(probeVideo(notAVideo)).rejects.toBeInstanceOf(
        VideoProcessingError
      );

      const error = await probeVideo(notAVideo).catch((e) => e);
      expect(error.stderr.length).toBeGreaterThan(0);
    }, FFMPEG_TIMEOUT);

    it('rejects when the input file does not exist', async () => {
      await expect(
        probeVideo(join(workDir, 'nope-missing.mp4'))
      ).rejects.toBeInstanceOf(VideoProcessingError);
    }, FFMPEG_TIMEOUT);
  });

  describe('transcodeToMp4', () => {
    it('normalises to h264 + aac while preserving duration and dimensions', async () => {
      const outputPath = join(workDir, 'normalised.mp4');
      await transcodeToMp4(fixturePath, outputPath);

      const output = await probeVideo(outputPath);
      expect(output.videoCodec).toBe('h264');
      expect(output.audioCodec).toBe('aac');
      expect(output.durationSeconds).toBeGreaterThan(1.8);
      expect(output.durationSeconds).toBeLessThan(2.2);
      // Source is already under the 1280px cap, so it passes through untouched
      expect(output.width).toBe(320);
      expect(output.height).toBe(240);

      const stats = await stat(outputPath);
      expect(stats.size).toBeGreaterThan(0);
    }, FFMPEG_TIMEOUT);

    it('rejects with a typed error when the input is not decodable', async () => {
      const notAVideo = join(workDir, 'garbage.mp4');
      await writeFile(notAVideo, 'still not a video');
      const outputPath = join(workDir, 'garbage-out.mp4');

      const error = await transcodeToMp4(notAVideo, outputPath).catch((e) => e);
      expect(error).toBeInstanceOf(VideoProcessingError);
      expect(error.stderr.length).toBeGreaterThan(0);
    }, FFMPEG_TIMEOUT);
  });

  describe('extractPosterFrame', () => {
    it('writes a jpeg poster frame at the source dimensions', async () => {
      const posterPath = join(workDir, 'poster.jpg');
      await extractPosterFrame(fixturePath, posterPath);

      const metadata = await sharp(posterPath).metadata();
      expect(metadata.format).toBe('jpeg');
      expect(metadata.width).toBe(320);
      expect(metadata.height).toBe(240);
    }, FFMPEG_TIMEOUT);

    it('rejects with a typed error when the input is not decodable', async () => {
      const notAVideo = join(workDir, 'poster-garbage.mp4');
      await writeFile(notAVideo, 'nope');

      const error = await extractPosterFrame(
        notAVideo,
        join(workDir, 'poster-garbage.jpg')
      ).catch((e) => e);
      expect(error).toBeInstanceOf(VideoProcessingError);
      expect(error.stderr.length).toBeGreaterThan(0);
    }, FFMPEG_TIMEOUT);
  });
});
