/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostersIndexRouteImport } from './routes/posters/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PostersSlugRouteImport } from './routes/posters/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReturnsRouteImport } from './routes/admin/returns'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed/account/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AuthedAccountWalletRouteImport } from './routes/_authed/account/wallet'
import { Route as AuthedAccountOrdersRouteImport } from './routes/_authed/account/orders'
import { Route as AuthedAccountAiCreationsRouteImport } from './routes/_authed/account/ai-creations'
import { Route as AuthedAccountOrdersIdRouteImport } from './routes/_authed/account/orders.$id'
import { Route as AuthedAccountOrdersIdReturnRouteImport } from './routes/_authed/account/orders.$id.return'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostersIndexRoute = PostersIndexRouteImport.update({
  id: '/posters/',
  path: '/posters/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PostersSlugRoute = PostersSlugRouteImport.update({
  id: '/posters/$slug',
  path: '/posters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedAccountWalletRoute = AuthedAccountWalletRouteImport.update({
  id: '/account/wallet',
  path: '/account/wallet',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountOrdersRoute = AuthedAccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountAiCreationsRoute =
  AuthedAccountAiCreationsRouteImport.update({
    id: '/account/ai-creations',
    path: '/account/ai-creations',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAccountOrdersIdRoute = AuthedAccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAccountOrdersRoute,
} as any)
const AuthedAccountOrdersIdReturnRoute =
  AuthedAccountOrdersIdReturnRouteImport.update({
    id: '/return',
    path: '/return',
    getParentRoute: () => AuthedAccountOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/posters/$slug': typeof PostersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/create': typeof CreateIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/posters': typeof PostersIndexRoute
  '/account/ai-creations': typeof AuthedAccountAiCreationsRoute
  '/account/orders': typeof AuthedAccountOrdersRouteWithChildren
  '/account/wallet': typeof AuthedAccountWalletRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account': typeof AuthedAccountIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/account/orders/$id': typeof AuthedAccountOrdersIdRouteWithChildren
  '/account/orders/$id/return': typeof AuthedAccountOrdersIdReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/posters/$slug': typeof PostersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/create': typeof CreateIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/posters': typeof PostersIndexRoute
  '/account/ai-creations': typeof AuthedAccountAiCreationsRoute
  '/account/orders': typeof AuthedAccountOrdersRouteWithChildren
  '/account/wallet': typeof AuthedAccountWalletRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account': typeof AuthedAccountIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/account/orders/$id': typeof AuthedAccountOrdersIdRouteWithChildren
  '/account/orders/$id/return': typeof AuthedAccountOrdersIdReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/posters/$slug': typeof PostersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/create/': typeof CreateIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/posters/': typeof PostersIndexRoute
  '/_authed/account/ai-creations': typeof AuthedAccountAiCreationsRoute
  '/_authed/account/orders': typeof AuthedAccountOrdersRouteWithChildren
  '/_authed/account/wallet': typeof AuthedAccountWalletRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/_authed/account/orders/$id': typeof AuthedAccountOrdersIdRouteWithChildren
  '/_authed/account/orders/$id/return': typeof AuthedAccountOrdersIdReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/returns'
    | '/admin/reviews'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/success'
    | '/posters/$slug'
    | '/admin/'
    | '/cart'
    | '/checkout'
    | '/create'
    | '/gallery'
    | '/posters'
    | '/account/ai-creations'
    | '/account/orders'
    | '/account/wallet'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account'
    | '/admin/orders'
    | '/admin/products'
    | '/account/orders/$id'
    | '/account/orders/$id/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/returns'
    | '/admin/reviews'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/success'
    | '/posters/$slug'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/create'
    | '/gallery'
    | '/posters'
    | '/account/ai-creations'
    | '/account/orders'
    | '/account/wallet'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account'
    | '/admin/orders'
    | '/admin/products'
    | '/account/orders/$id'
    | '/account/orders/$id/return'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin'
    | '/admin/returns'
    | '/admin/reviews'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/success'
    | '/posters/$slug'
    | '/admin/'
    | '/cart/'
    | '/checkout/'
    | '/create/'
    | '/gallery/'
    | '/posters/'
    | '/_authed/account/ai-creations'
    | '/_authed/account/orders'
    | '/_authed/account/wallet'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/_authed/account/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/_authed/account/orders/$id'
    | '/_authed/account/orders/$id/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  PostersSlugRoute: typeof PostersSlugRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  PostersIndexRoute: typeof PostersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posters/': {
      id: '/posters/'
      path: '/posters'
      fullPath: '/posters'
      preLoaderRoute: typeof PostersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/posters/$slug': {
      id: '/posters/$slug'
      path: '/posters/$slug'
      fullPath: '/posters/$slug'
      preLoaderRoute: typeof PostersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/account/wallet': {
      id: '/_authed/account/wallet'
      path: '/account/wallet'
      fullPath: '/account/wallet'
      preLoaderRoute: typeof AuthedAccountWalletRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/orders': {
      id: '/_authed/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthedAccountOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/ai-creations': {
      id: '/_authed/account/ai-creations'
      path: '/account/ai-creations'
      fullPath: '/account/ai-creations'
      preLoaderRoute: typeof AuthedAccountAiCreationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/orders/$id': {
      id: '/_authed/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AuthedAccountOrdersIdRouteImport
      parentRoute: typeof AuthedAccountOrdersRoute
    }
    '/_authed/account/orders/$id/return': {
      id: '/_authed/account/orders/$id/return'
      path: '/return'
      fullPath: '/account/orders/$id/return'
      preLoaderRoute: typeof AuthedAccountOrdersIdReturnRouteImport
      parentRoute: typeof AuthedAccountOrdersIdRoute
    }
  }
}

interface AuthedAccountOrdersIdRouteChildren {
  AuthedAccountOrdersIdReturnRoute: typeof AuthedAccountOrdersIdReturnRoute
}

const AuthedAccountOrdersIdRouteChildren: AuthedAccountOrdersIdRouteChildren = {
  AuthedAccountOrdersIdReturnRoute: AuthedAccountOrdersIdReturnRoute,
}

const AuthedAccountOrdersIdRouteWithChildren =
  AuthedAccountOrdersIdRoute._addFileChildren(
    AuthedAccountOrdersIdRouteChildren,
  )

interface AuthedAccountOrdersRouteChildren {
  AuthedAccountOrdersIdRoute: typeof AuthedAccountOrdersIdRouteWithChildren
}

const AuthedAccountOrdersRouteChildren: AuthedAccountOrdersRouteChildren = {
  AuthedAccountOrdersIdRoute: AuthedAccountOrdersIdRouteWithChildren,
}

const AuthedAccountOrdersRouteWithChildren =
  AuthedAccountOrdersRoute._addFileChildren(AuthedAccountOrdersRouteChildren)

interface AuthedRouteChildren {
  AuthedAccountAiCreationsRoute: typeof AuthedAccountAiCreationsRoute
  AuthedAccountOrdersRoute: typeof AuthedAccountOrdersRouteWithChildren
  AuthedAccountWalletRoute: typeof AuthedAccountWalletRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountAiCreationsRoute: AuthedAccountAiCreationsRoute,
  AuthedAccountOrdersRoute: AuthedAccountOrdersRouteWithChildren,
  AuthedAccountWalletRoute: AuthedAccountWalletRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminRouteChildren {
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  PostersSlugRoute: PostersSlugRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  PostersIndexRoute: PostersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
