/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostersIndexRouteImport } from './routes/posters/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountAiCreationsRouteImport } from './routes/account/ai-creations'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as PostersCategorySlugRouteImport } from './routes/posters/$category.$slug'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostersIndexRoute = PostersIndexRouteImport.update({
  id: '/posters/',
  path: '/posters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAiCreationsRoute = AccountAiCreationsRouteImport.update({
  id: '/account/ai-creations',
  path: '/account/ai-creations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const PostersCategorySlugRoute = PostersCategorySlugRouteImport.update({
  id: '/posters/$category/$slug',
  path: '/posters/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/account/ai-creations': typeof AccountAiCreationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/account': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/create': typeof CreateIndexRoute
  '/posters': typeof PostersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/posters/$category/$slug': typeof PostersCategorySlugRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/ai-creations': typeof AccountAiCreationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/create': typeof CreateIndexRoute
  '/posters': typeof PostersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/posters/$category/$slug': typeof PostersCategorySlugRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/account/ai-creations': typeof AccountAiCreationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/create/': typeof CreateIndexRoute
  '/posters/': typeof PostersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/posters/$category/$slug': typeof PostersCategorySlugRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account/ai-creations'
    | '/account/orders'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/success'
    | '/account'
    | '/admin/'
    | '/cart'
    | '/checkout'
    | '/create'
    | '/posters'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/posters/$category/$slug'
    | '/admin/orders'
    | '/admin/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/ai-creations'
    | '/account/orders'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/success'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/create'
    | '/posters'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/posters/$category/$slug'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account/ai-creations'
    | '/account/orders'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/success'
    | '/account/'
    | '/admin/'
    | '/cart/'
    | '/checkout/'
    | '/create/'
    | '/posters/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/posters/$category/$slug'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AccountAiCreationsRoute: typeof AccountAiCreationsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  PostersIndexRoute: typeof PostersIndexRoute
  PostersCategorySlugRoute: typeof PostersCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posters/': {
      id: '/posters/'
      path: '/posters'
      fullPath: '/posters'
      preLoaderRoute: typeof PostersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/ai-creations': {
      id: '/account/ai-creations'
      path: '/account/ai-creations'
      fullPath: '/account/ai-creations'
      preLoaderRoute: typeof AccountAiCreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/posters/$category/$slug': {
      id: '/posters/$category/$slug'
      path: '/posters/$category/$slug'
      fullPath: '/posters/$category/$slug'
      preLoaderRoute: typeof PostersCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AccountAiCreationsRoute: AccountAiCreationsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  AccountIndexRoute: AccountIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  PostersIndexRoute: PostersIndexRoute,
  PostersCategorySlugRoute: PostersCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
